version: "3"

services:
  db:
    image: mysql:5.7
    container_name: express-ts-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express_ts
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./volumes/db/data:/var/lib/mysql
      - ./volumes/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
